### PR TITLE
modified aacraid to be used as a check-mk plugin

### PR DESCRIPTION
**Pull request by IvanRossi**
You might be interested in merging our (minor) work that transformed aacraid.py in a [check-mk](http://mathias-kettner.com/check_mk.html) agent plugin

### CODE REVIEW

**Comment by evgeni** [comment]
nack.

can you please make it co-existing with the original code? i still want my normal cli binary and the daemon to be there.

**Comment by evgeni** [comment]
ping?

**Comment by IvanRossi** [comment]
refatoring the code to accomodate that is  NOW very low priority. maybe in the future...
Thank you anyway.

**Comment by evgeni** [comment]
ok, closing then until you get some time.

**Pull request closed without merging**
